name: Bug report
description: File a bug report for the Maker CLI.
labels: ["bug", "triage"]

body:
  - type: input
    attributes:
      label: "Version:"
      description: "What version of the Maker CLI are you experiencing this issue with?"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Command(s):"
      description: "What command(s) does this issue relate to?"
      multiple: true
      options:
        - Config
        - Create
        - Dev
        - Help
        - Link
        - Restart
        - Stop

  - type: textarea
    attributes:
      label: "Description:"
      description: "Describe the issue in depth, including reproduction steps and the output."
    validations:
      required: true

  - type: input
    attributes:
      label: "Operating system:"
      description: "Name and version."
    validations:
      required: true

  - type: input
    attributes:
      label: "Node.js version:"
      description: "You can find the version of Node.js by running `node -v` in your terminal."
    validations:
      required: true

  - type: input
    attributes:
      label: "Stream Deck version:"
      description: "What version of Stream Deck is impacted by this issue, if any?"
